### ISSUE TITLE
Run tests in visual studio

### ISSUE THREAD

**Issue by Mattias1** [beardgame/ui#23]
## 🆙 Improvement proposal
Currently the tests are not discovered in visual studio. To fix that I've added the _xunit.runner.visualstudio_ and the _Microsoft.NET.Test.Sdk_ packages to the test project, but that breaks the netstandard build (it works for the net462 build).
If you don't care about the netstandard targeting (for example after you switched to .NET Core), you could maybe add those two packages for us visual studio users ;)

## Context
You can't run tests from visual studio now. Right now you can create a PR to let the CI run the tests for you. Maybe it works from the command line, didn't try that.

**Comment by tomrijnbeek** [comment]
I believe `Microsoft.NET.Test.SDK` is the big requirement now, and that the runner is no longer necessary. I don't use Visual Studio myself, so I can't test, but it sounds like we may want to double check our dependencies.
