### ISSUE TITLE
Control dimensions vs bounding box

### ISSUE THREAD

**Issue by tomrijnbeek** [beardgame/ui#8]
Right now a control has dimensions, and it is silently assumed that a control always fully occupies it. This is not necessarily true for two type of controls I can think of, potentially more:

1. A control whose content does not have a fixed size. An example of this is a notifications component. The dimensions of the wrapper notification control tell the control how much space the notifications are allowed to take up, but they do not necessarily need to always occupy the full space. You could imagine that it would always fit in at most as many notifications as possible.
2. Non-rectangular controls. A control may have an L shape for example (a sidebar sticking out or something similar). 

In both cases, the actual shape of the control does not match up with the control's bounding box, in particular for mouse input. That means that any controls below do not get the event when hovering over the rectangular bounding box around the control.

This could be solved by not having a control grouping these things together, but instead adding the controls to the parent control directly. This has several disadvantages though:

1. It is a bit messy, since the model hierarchy no longer lines up with the view hierarchy.
2. The parent control may not necessarily be the direct parent, meaning you have to find some control a few levels up in the hierarchy to get the bounding boxes right.
3. It is less easy to maintain rendering order if there are multiple systems adding controls to some sort of root control.

All in all, it seems like a very inelegant solution to just move things into the parent.

Marking the wrapper control as a 0 size so it doesn't capture any mouse events also means the children won't get any mouse event, so it is also not a valid solution.

The root of the problem is that we do not necessarily want the `Frame` of a control (which is mostly there for drawing dimensions) to be exactly the same as the capture area for the mouse input. I propose several possible solutions for this:

1. Allow marking controls as "see-through". Mouse events will propagate into it, but it can never be the leaf of a mouse propagation path. That means: if none of the control's children receive the mouse event, the control is ignore and the mouse event propagated to the control below it. This is quite a flexible solution, and allows controls to be bigger than they are without taking up events. This even opens up having multiple "layers" of controls all taking up the whole screen, each dealing with a separate domain of logic and its UI. Here the interesting discussion is whether see-through will be the default, similar to how components have to explicitly specify they can be focused.
2. Better support for dynamic control sizes. This solves the first problem (with notifications), but not necessarily the problem with non-rectangular controls. It basically would allow controls to have their size changed dynamically, for example by specifying in what direction a control should grow.
3. Allow controls to override the mouse-bounding box check. Basically this puts all the control (no pun intended) in the hands of the control, by making it possible for them to completely ignore the default behaviour, and write their own mouse-intersection check. This opens up a lot of options, including control dimensions that are not axis-aligned. However, I am not a big fan of this solution, since it would mean that all controls in the situations described above have to implement (pretty much) the same behaviour, and I don't believe the level of control beyond the other two solutions above is really a common use case.
4. Give controls a more complex bounding area for mouse interactions. Instead of using the frame, the control could have an additional property that defines what are it occupies. This could be a box, a circle, a hexagon, or a composite of all of these. These bounding areas could abstract the mouse position intersection logic away from solution 3 above, while providing almost the same level of control. The default would be for a control to have a bounding area that is a box with the same size as its frame.

Of all the solutions, I believe option 1 is the best. While in the future we may still build something like option 3 or 4 for more complex control interactions, I don't think that would devalue option 1 as a solution, since it is still a really nice abstraction that will cover 95% of the cases with little to no work to the library user.

**Comment by amulware** [comment]
If we want 2, I'd recommend going straight for a constraint-based layout which has many other advantages and supports complex layouts without a lot of hierarchy.

I agree that 1 would be the way to go for now, it's the easiest.

A note on 3: You could inject the behaviour instead of overriding it, to make it a bit more flexible.

4 I'm really not a big fan of unless maybe using 3 and injecting the behaviour so that most controls can still ave the simple bounding box check.

**Comment by tomrijnbeek** [comment]
Option 1 it is then. PR forthcoming.
